### ISSUE TITLE
Call local_time in a presenter class

### ISSUE THREAD

**Issue by chrisgeek** [basecamp/local_time#103]
Callling `local_time` in a presenter class returns an error, `undefined method local_time for presenter`. Does this mean the method can only be called on the client side (view) ?

**Comment by javierav** [comment]
You are right. `local_time` is defined as a helper in [local_time_helper.rb](https://github.com/basecamp/local_time/blob/master/app/helpers/local_time_helper.rb). If you use Draper gem for presenter, you can do `h.local_time` for access to defined helpers in Rails...

**Comment by josefarias** [comment]
The provided helpers can be called anywhere a standard rails helper can be called. Usually, that means calling them in view templates on the server. But they can be used in other places by including rails helpers through any number of means. Up to you how you decide to do that – but I would recommend doing it sparingly.
