### ISSUE TITLE
local_time (2.1.0): Using %Z to output timezone of a date it says CEST when it is not summer in any way.

### ISSUE THREAD

**Issue by barrerajl** [basecamp/local_time#105]
This:
`local_time(time, '%Z')`

 outputs:
`<time datetime="2021-01-21T15:00:00Z" data-local="time" data-format="%Z">UTC</time>`

Which seems fine but it renders:
`<time datetime="2021-01-21T15:00:00Z" data-local="time" data-format="%Z" title="January 21, 2021 at 4:00pm CEST" data-localized="" aria-label="CEST">CEST</time>`

We are displaying the date as of today (21st december 2020) and should be CET, it is not summer :-(

**Comment by 1klap** [comment]
I noticed the same problem, I think it comes from here: 
https://github.com/basecamp/local_time/blob/5edd54f5e1e79bcb8e512ba1f89077241f55fc8c/lib/assets/javascripts/src/local-time/helpers/strftime.coffee#L40-L57
and the fact that for Firefox 96 and Chrome 97 in Central Europe `new Date()` (or `new Date("2022-02-08T15:52:14Z")`) return a Date object with the following `toString()` result: `"Tue Feb 08 2022 16:52:14 GMT+0100 (Central European Standard Time)"` 

That string matches this case:
https://github.com/basecamp/local_time/blob/5edd54f5e1e79bcb8e512ba1f89077241f55fc8c/lib/assets/javascripts/src/local-time/helpers/strftime.coffee#L44-L46
and Central European **Standard** Time is abbreviated as CEST which in this case is equal to the Daylight Saving Zone zone Central European **Summer** Time, which is not in effect at that point in time.

This [SO article](https://stackoverflow.com/questions/51728862/central-european-standard-time-instead-of-cet-for-date-prototype-tostring/51729281) mentions the same problem and a response mentions that the timezone string is not fully specified according to [ECMA2018](https://262.ecma-international.org/9.0/#sec-timezoneestring) and [ECMA2021 norms](https://262.ecma-international.org/#sec-date.prototype.tostring)

**Comment by 1klap** [comment]
In order to circumvent this issue, I hardcoded the detection of this one case.
In the minified JS i replaced 
```javascript
s.match(/\b(\w)/g).join("")
```
with
```javascript
(s=="Central European Standard Time"?"CET":s.match(/\b(\w)/g).join(""))
```
and I can confirm that this solves the issue
