### ISSUE TITLE
JS not running

### ISSUE THREAD

**Issue by dchacke** [basecamp/local_time#106]
I'm following the Readme step by step but the client-side part doesn't seem to be running at all: the markup generated on the server by the `local_time` function remains untouched in the DOM.

Is this gem broken?

More details here: https://stackoverflow.com/questions/65388487/rails-local-time-gem-not-running-js

**Comment by Merovex** [comment]
https://stackoverflow.com/questions/65388487/rails-local-time-gem-not-running-js/65522146#65522146

Responded

**Comment by paulanunda** [comment]
`yarn add local-time` worked for me (ran in a new rails 6 app)

![image](https://user-images.githubusercontent.com/155981/103570612-6d8e4280-4e97-11eb-983e-52508d0e359c.png)

**Comment by yournumberone** [comment]
> `yarn add local-time` worked for me (ran in a new rails 6 app)
> 
> ![image](https://user-images.githubusercontent.com/155981/103570612-6d8e4280-4e97-11eb-983e-52508d0e359c.png)

still not working on mobile devices

**Comment by lordofthedanse** [comment]
For some reason, I needed to change `import LocalTime from "local-time"` to  `import * as LocalTime from "local-time"`.

Then all worked as expected.

**Comment by josefarias** [comment]
Instructions have been updated: https://github.com/basecamp/local_time/pull/139

Some slight changes may be needed depending on each application's setup. But those should work for most people out-of-the-box.
