### ISSUE TITLE
how? i18n 

### ISSUE THREAD

**Issue by yournumberone** [basecamp/local_time#108]
I don't understand why the issue #53 was closed. I created my version of the file i18n.coffee, required it in my application.js, but it still doesn't work for me. Sorry, but not detailed enough documentation for i18n.

**Comment by denkozlovs** [comment]
same here, it ignores LocalTime.config alteration. on the terminal I can see all the changes, but result stay unchanged
I'm trying:
- remove `data-localized` flag from <time> tag
- remove generated result from <time></time>
- run `LocalTime.run()`

It generates back what was there previously (built-in `en` translation), ignoring my configuration. even if I try to alter `en`, nothing changes

I believe, it forces us to use new webpack approach, but my current project relies on old assets/javascript without any start() things...

**Comment by denkozlovs** [comment]
my current workaround is:
- open up https://github.com/basecamp/local_time/blob/main/app/assets/javascripts/local-time.js
- copy
- paste into https://beautifier.io
- copy result
- create app/assets/javascripts/localtime.js
- paste there
- update en translation
- replace `//= require local-time` with `//=require localtime`

**Comment by yournumberone** [comment]
`            function() {
                e.config.locale = "en", e.config.defaultLocale = "en"
            }.call(this)`
how upd this?

**Comment by yournumberone** [comment]
I changed it to `function() {  e.config.locale = navigator.language || navigator.userLanguage, e.config.defaultLocale = "en" }.call(this)`

**Comment by fourseven** [comment]
We've just run into this as well, was using the gem on a rails 5.2.x codebase - it looks like the gem calls `LocalTime.start()` in the bundled JS and that runs before you can override the config - so we deleted the gem, used a `time_tag()` in the views with the data attributes we needed (based off this project's readme) and used the npm package with the recommended import and our specific config THEN the `LocalTime.start()`.
