### ISSUE TITLE
doesn't work on mobile devices

### ISSUE THREAD

**Issue by yournumberone** [basecamp/local_time#109]
ios safari console: 
TypeError: undefined is not an object (evaluating 's[r=o[n]]')

**Comment by ykamin-booth** [comment]
Did you ever figure this out?

**Comment by josefarias** [comment]
If you could share a minimal reproduction example that'd be very useful in determining why it's not working for you.

Something like this:

```html
<!DOCTYPE html>
<html>
<head>
  <script>
    // include latest umd build here

    window.LocalTime.start()
  </script>
</head>
<body>
  <time datetime="2023-06-22T20:36:22-06:00" data-local="time-ago">X</time>
</body>
</html>
```

Closing for now – will reopen if a reproduction is provided. Thanks!
