### ISSUE TITLE
Does not appear to work in Rails 7 using import-map (new Rails default)

### ISSUE THREAD

**Issue by Merovex** [basecamp/local_time#113]
Howdy, I'm building an app from scratch in Rails 7 Alpha. This uses import maps.

In the import map, I have `pin "helpers/local-time"`, which works as expected. I can import the file no problem. I import thusly:

```
import "helpers/local-time"
import LocalTime from "helpers/local-time"
```

I get the following error:

```
SyntaxError: Importing binding name 'default' cannot be resolved by star export entries. 
http://localhost:3000/assets/es-module-shims.min.js
```

I know that's in the Shim, not in local time, but the error traces to the following location. I'm not a JS guy, so not quite sure how to correct in 

```
function processScript(e) {
    if (e.ep)
      return;
    if (null !== e.getAttribute("noshim"))
      return;
    if (!e.src && !e.innerHTML)
      return;
    e.ep = true;
    const t = ar > 0;
    const s = sr > 0;
    t && ar++;
    s && sr++;
    const a = topLevelLoad(e.src || `${r}?${Ne++}`, getFetchOpts(e), !e.src && e.innerHTML, !c, t && tr).catch((e => {
      setTimeout((() => {
        throw e
      }));
      pe(e)
    }));
    t && (tr = a.then(readyStateCompleteCheck));
    s && a.then(domContentLoadedCheck)
  }
```

**Comment by phillipspc** [comment]
I was getting a similar error 

`SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.` 

after using `./bin/importmap pin local-time --download`. If I exclude the `--download` flag, and just use the CDN version, this error goes away. 🤷‍♂️

**Comment by 1klap** [comment]
I have the same issue...using importmaps with the downloaded file causes problem while using the CDN works perfectly.
I don"t understand why that is the case, why does it make a difference from where the file is loaded...

**Comment by 1klap** [comment]
Ok, the problem seems to come from the js module that is bundled with this gem. The asset pipeline serves that one instead the one in `vendor/javascript` and it seems to have problems with the ESM loading.

My workaround to still use importmaps and downloaded js modules was to rename the file to avoid this conflict.

* ` $ bin/importmaps pin local-time --download`
* rename `vendor/javascript/local-time.js` to `vendor/javascript/local-time-cdn.js`
* change pin in `importmap.rb` to `pin "local-time-cdn"`
* load LocalTime from that module instead
```javascript
import LocalTime from "local-time-cdn"
LocalTime.start()
```

Tested in Firefox 96 and Chrome 97

**Comment by Merovex** [comment]
Back to this again. Rails 7 application, using the CDN. The following code did not work:

```
import * as LocalTime from "local-time"
LocalTime.start()
```

On a hunch, I tried the following, which worked perfectly:

```
import LocalTime from "local-time"
LocalTime.start()
```

This uses the CDN version. 🤷🏻‍♂️

**Comment by josefarias** [comment]
@1klap's [reply](https://github.com/basecamp/local_time/issues/113#issuecomment-1029183211) hits the nail on the head. Thanks!

Note that there's a way to still reference the library in JS by its original name. Just add the `to:` option in `config/importmap.rb`:

```ruby
pin "local-time", to: "vendored-local-time.js"
```

Then, you can:
```js
import LocalTime from "local-time"
LocalTime.start()
```

Crucially, the vendored file needs to be renamed to something other than `local-time.js`.

This won't be a problem anymore once https://github.com/basecamp/local_time/pull/134 is released.

**Comment by vietqhoang** [comment]
@josefarias Thanks for addressing the problem in your recent changes. Are there plans to do a version bump with the new changes?

**Comment by josefarias** [comment]
Hey @vietqhoang, I plan to spend my upcoming [cooldown](https://basecamp.com/shapeup/2.2-chapter-08#cool-down) tying up loose ends in this library — including cutting a new release. So no promises, but it might happen soon.

In the meantime, you can vendor the JS library (bundled versions are checked into the repo [here](https://github.com/basecamp/local_time/tree/main/app/assets/javascripts)), and you can [point your Gemfile version](https://bundler.io/guides/gemfile.html) to the main branch for the Ruby library.

**Comment by mjankowski** [comment]
With downloading the new default in importmap-rails - https://github.com/rails/importmap-rails/pull/217 - I suspect people using this lib are going to bump into this issue more. Thanks for the workaround guidance! Would love to see version bump with changes, but noted on priorities.

**Comment by marckohlbrugge** [comment]
Could someone share up-to-date and complete instructions on how make `local_time` work with the latest `importmap-rails`? I tried following @1klap's approach, but `bin/importmap pin local-time --download` returns `Couldn't find any packages in ["local-time", "--download"] on jspm`

**Comment by josefarias** [comment]
@marckohlbrugge, are you using the latest `importmap-rails`? If so, then I don't think the `--download` option works anymore as it's not needed, per https://github.com/rails/importmap-rails/pull/217.

This does it for me:
```sh
❯ rails new test_app
❯ git add .
❯ git commit -m "Initial commit"
❯ bin/importmap pin local-time
#=> Pinning "local-time" to vendor/javascript/local-time.js via download from https://ga.jspm.io/npm:local-time@2.1.0/app/assets/javascripts/local-time.js
❯ mv vendor/javascript/local-time.js vendor/javascript/vendored-local-time.js
❯ sed -i '' '$ s/pin "local-time" # @2.1.0/pin "local-time", to: "vendored-local-time.js" # @2.1.0/' ./config/importmap.rb
❯ git add .
❯ git diff --cached
```

Results in:
```diff
diff --git a/config/importmap.rb b/config/importmap.rb
index bc060ed..a3aa833 100644
--- a/config/importmap.rb
+++ b/config/importmap.rb
@@ -5,3 +5,4 @@ pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
 pin "@hotwired/stimulus", to: "stimulus.min.js"
 pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
 pin_all_from "app/javascript/controllers", under: "controllers"
+pin "local-time", to: "vendored-local-time.js" # @2.1.0
diff --git a/vendor/javascript/vendored-local-time.js b/vendor/javascript/vendored-local-time.js
new file mode 100644
index 0000000..bd59480
--- /dev/null
+++ b/vendor/javascript/vendored-local-time.js
@@ -0,0 +1,2 @@
+var r="undefined"!==typeof globalThis?globalThis:"undefined"!==type [truncated...]
```

The readme should take you the rest of the way.

Note that renaming the vendored file and editing `importmap.rb` won't be necessary when we cut the new release.

**Comment by dwightwatson** [comment]
I've using the latest version of `importmap-rails`. Having the same issue without the `--download` argument.

```
➜  app git:(main) ✗ bin/importmap pin local-time
Couldn't find any packages in ["local-time"] on jspm
```

Tried on a fresh Rails app and have the same result.

```
➜  Sites cd blank 
➜  blank git:(main) ✗ bin/importmap pin local-time 
Couldn't find any packages in ["local-time"] on jspm
```

Relevant: https://github.com/rails/importmap-rails/issues/231

**Comment by josefarias** [comment]
Managed to replicate, no clue why it was working for me yesterday 🤷🏻‍♂️ 

Passing `--from=jspm.io` seems to work:
```bash
❯ bin/importmap pin local-time
#=> Couldn't find any packages in ["local-time"] on jspm
❯ bin/importmap pin local-time --from=jspm.io
#=> Pinning "local-time" to vendor/javascript/local-time.js via download from https://ga.jspm.io/npm:local-time@2.1.0/app/assets/javascripts/local-time.js
```

Looks like a breaking change in the jspm API. Made a PR to fix in `importmap-rails`: https://github.com/rails/importmap-rails/pull/234

**Comment by josefarias** [comment]
I've just released the newest version. This should now work without having to rename anything. So:

```sh
❯ rails new test_app
❯ cd test_app
❯ bundle add local_time
❯ bundle install
❯ bin/importmap pin local-time # works now per https://github.com/rails/importmap-rails/pull/234#issuecomment-1892668735
#=> Pinning "local-time" to vendor/javascript/local-time.js via download from https://ga.jspm.io/npm:local-time@3.0.2/app/assets/javascripts/local-time.es2017-esm.js
```

Then follow the readme to import and start the library. Let me know if you run into trouble, preferably creating a new issue if unrelated to this one.

**Comment by mjankowski** [comment]
Thanks for quick turnaround -- works as expected after version bump.
