### ISSUE TITLE
any plans for auto refresh for local_time_ago?

### ISSUE THREAD

**Issue by RohitVenturit** [basecamp/local_time#120]
Hi team,
    local_time_ago is a cool feature but it does not refresh automatically, can we have it down the line in the near future?

**Comment by josefarias** [comment]
Hey! `local_time_ago` should, in fact, be refreshing automatically once a minute.

If you could share a minimal reproduction of this – that'd be very useful in finding out why it's not working for you. Closing for now.

Something like

```html
<!DOCTYPE html>
<html>
<head>
  <script>
    // include latest umd build here

    window.LocalTime.start()
  </script>
</head>
<body>
  <time datetime="2023-06-22T20:36:22-06:00" data-local="time-ago">X</time>
</body>
</html>

```

Thanks!
