### ISSUE TITLE
Is this gem still maintained

### ISSUE THREAD

**Issue by jclusso** [basecamp/local_time#125]
I was looking at this gem and it appears it hasn't received any updates in about 4 years. Is this gem still being used by Basecamp or has there been a switch to something else? Wondering if this is going to be maintained anymore or if there is a better way to do this?

**Comment by brunoprietog** [comment]
They still use it, but I don't know why they don't maintain it

**Comment by northeastprince** [comment]
cc @afcapel

**Comment by afcapel** [comment]
We're still using it in both Basecamp and Hey. We haven't made any changes because we didn't have the need. The current feature is fairly complete, but we would surely update it if there was a compelling reason.

**Comment by brunoprietog** [comment]
@afcapel thanks for replying. I understand that you consider that no changes are needed, but it would be great if you could accept pull requests to improve the installation process, especially with importmap in Rails. Also, there is currently an accessibility issue, as html time elements should not have aria-label attribute. There are some open pr that attempt to address these. Would you be willing to accept something like this and update the gem? I could open up other pr if that sounds better to you. Thanks!
