### ISSUE TITLE
Feature request: Option to output just the converted time as a string without the time tag

### ISSUE THREAD

**Issue by nickjj** [basecamp/local_time#129]
Hi,

Currently the docs mention that: `<%= local_time(comment.created_at) %>`

Will render:

```html
<time data-format="%B %e, %Y %l:%M%P"
      data-local="time"
      datetime="2013-11-27T23:43:22Z">November 27, 2013 11:43pm</time>
```

Which then gets converted client-side to:

```html
<time data-format="%B %e, %Y %l:%M%P"
      data-local="time"
      datetime="2013-11-27T23:43:22Z"
      title="November 27, 2013 6:43pm EDT"
      data-localized="true">November 27, 2013 6:43pm</time>
```

90% of the time this is fine and what you want but sometimes you may want the converted date to be presented in a custom way, such as in the `title=` attribute of an element.

For example, I have this use case:

```html
<a href="#answer-<%= answer.id %>">
  <%= local_time_ago(answer.created_at) %>
</a>
<% if answer.updated_at > answer.created_at %>
  <span title="<%= answer.updated_at %>">(edited)</span>
<% end %>
```

That produces:

```html
<time datetime="2022-11-27T19:42:56Z"
      data-local="time-ago"
      title="November 27, 2022 at 2:42pm EST"
      aria-label="16 hours ago">16 hours ago</time>

<span title="2022-11-27 21:22:32 UTC">(edited)</span>
```

And here is the problem. I'd like the `span`'s `title=` to have the relative time ago but there's no way to do that at the moment.

It would be great if we could do `<%= local_time(comment.created_at, without_tag: true) %>` or whatever you decide to name it, but the intent here would be that in the above example that would output `November 27, 2022 at 2:42pm EST` and if you used `<%= local_time_ago(answer.created_at, without_tag: true) %>` it would produce `16 hours ago`.

That would let folks pick and choose to display a nicely formatted time or relative time in a custom way. `without_tag` would default to `false` to remain backwards compatible and be the right choice most of the time.

What do you think?

**Comment by MatheusRich** [comment]
I have a similar use case, where I want a dropdown (select) of available event datetimes, but I would like to show them in the user's local time.

**Comment by MatheusRich** [comment]
While not a full solution to this, I created a `local-time` Stimulus controller that works similarly to this gem. This allowed me to update the text content of a `option` tag to the user's local time.

```js
import { Controller } from "@hotwired/stimulus"

const locale = document.documentElement.lang
const dateFormatter = new Intl.DateTimeFormat(locale, { timeStyle: "full" }) // Tweak this for different formats, or event pass it as a controller value to make it configurable

export default class extends Controller {
  connect() {
    const datetime = new Date(this.element.value) // I'm using the element's value here, but you could use a data attribute, if you prefer
    const formattedDatetime = dateFormatter.format(datetime)

    this.element.textContent = formattedDatetime
  }
}
```

--- 

I guess we could make `local_time` to work without that if we could pass a different selector to the constructor, instead of this constant:

https://github.com/basecamp/local_time/blob/5edd54f5e1e79bcb8e512ba1f89077241f55fc8c/lib/assets/javascripts/src/local-time/controller.coffee#LL7C5-L7C5

Alternatively, we could change the constant to work with non-time tags by not requiring the `time` tag in the selector and using a data attribute:

```js
SELECTOR = "[data-local-time][data-local]:not([data-localized])"
```

We gotta be careful with such a change since it's likely to be a breaking change.

**Comment by josefarias** [comment]
This is an interesting idea but unfortunately not in the cards at the moment. It's just not what this library was built to do.

This is the first workaround that comes to mind:
```html
<!DOCTYPE html>
<html>
<head>
  <script>
    // include latest umd build here

    window.LocalTime.start()
  </script>
</head>
<body>
  <time id="updated_at" datetime="2023-06-22T20:36:22-06:00" data-local="time-ago">X</time>
  <span id="foo">(edited)</span>

  <script>
    document.getElementById("foo").setAttribute("title", document.getElementById("updated_at").innerText)
  </script>
</body>
</html>
```

This would let you still leverage LocalTime without having to re-implement its inner workings.

**Comment by nickjj** [comment]
This doesn't quite solve the issue.

In my example `updated_at` is never defined as a DOM element through local_time, but in your example it is. In my example `created_at` is defined as a DOM element through local_time and then the `updated_at` value is displayed as the title element of a different element (the next adject sibling's title).

**Comment by josefarias** [comment]
Hi @nickjj, it should be possible to render `updated_at` to the dom as required by my example and hide it. Sorry it wasn't clear but in my example the `updated_at` element wasn't meant to be analogous to your `created_at` element – i just didn't think to hide it.

A couple of ways of hiding come to mind. You could use css (i.e. `display: none;`) or render it inside a `<template>` element. That way it'll be hidden in the UI but still reference-able via JS.

You can set `aria-hidden='true'` to make sure it doesn't show up in assistive technologies.

**Comment by nickjj** [comment]
That makes sense, thanks. I'm using StimulusJS.

Would it be possible to have it load after LocalTime parsed the time elements without using a dedicated Stimulus controller for just setting this title? That's because I have these types of outputs happen in a number of spots and also in template partials that get broadcast through Turbo Streams.

**Comment by josefarias** [comment]
@nickjj I'd say using a stimulus controller exclusively for setting this title is reasonable.

Note that both Stimulus and LocalTime use mutation observers to watch for page changes. There might be some race conditions there, but I haven't checked. Adding a small timeout should suffice if the problem arises.

Now, let's take a step back and look at what you're gaining here, because it might not be worth it.

This library is meant for rendering UTC `<time>` elements for caching across users in different time zones - and displaying their local time via JS manipulation. The fact that it has a relative time subsystem is an implementation detail, not a primary function of the library.

If what you're after is just the relative time, and you're not going to be caching across users, then it might be better to just re-implement the subsystem in ruby (despite what I said in my first comment). I'm sure there are gems already out there that do that, too.

It all ultimately depends on what you're building and how.

**Comment by nickjj** [comment]
I am caching the response. It's a list of replies from X users (similar idea to GitHub issue comments).

These replies may or may not have been edited. If it's edited I was trying to display an `(edited)` span which showed the time in a nicely formatted way in its title. I wanted to do this client side so that the server side UTC time would be converted in JS, because otherwise I wouldn't be able to cache the templates since every user would have different locally converted times.

As an experiment I ended up replacing this library with a Stimulus controller and Day.js, but I did notice that when I attached this Stimulus controller to the parent div of the replies, new replies that were broadcasted didn't get their times updated based on the `connect()` function of the Stimulus controller. I'm thinking going back to local_time will have the same problem. It's not clear on how to solve this so that newly broadcasted items have a Stimulus controller's connect function run against it.

**Comment by josefarias** [comment]
> when I attached this Stimulus controller to the parent div of the replies, new replies that were broadcasted didn't get their times updated based on the connect() function of the Stimulus controller

The stimulus controller should be attached to the broadcasted elements if you want their `connected` callbacks to run. Or you could register the broadcasted elements as targets of the controller and have their `targetConnected` callbacks run. But that's out of scope for LocalTime. I'd suggest reviewing the Stimulus docs and raise the issue in the Stimulus repo if something isn't working as expected.

**Comment by nickjj** [comment]
Thanks, it does work as expected on the Stimulus side of things. I was trying to avoid having something like `data-controller="time"` defined 50 times for 50 replies. I'll check into `targetConnected`, that sounds like it'll do the trick to allow defining the controller once and having the target attached to each broadcasted element.
