### ISSUE TITLE
local_time_ago changes format for older timestamps

### ISSUE THREAD

**Issue by rcuhljr** [basecamp/local_time#133]
When using the `local_time_ago` helper with a date in the past, it will initially load into the page displaying a message like this
![image](https://github.com/basecamp/local_time/assets/206958/404cb6b3-6e1a-42a5-86ee-98ddf19413a3)
Not the `on` at the beginning of the generated date display.

However if I then leave the page idle and the timeout that triggers an update fires, it replaces the message but uses a different format without the `on`.

![image](https://github.com/basecamp/local_time/assets/206958/264c987a-17bc-4b75-a5a5-523f55474876)

**Comment by josefarias** [comment]
Not seeing this behavior on `main`. Could you come up with a minimal reproduction example, please? Something like this:

```html
<!DOCTYPE html>
<html>
<head>
  <script>
    // include latest umd build here

    window.LocalTime.start()
  </script>
</head>
<body>
  <time datetime="2023-06-22T20:36:22-06:00" data-local="time-ago">X</time>
</body>
</html>
```

Closing in the meantime. Thanks!
