### ISSUE TITLE
24h support for relative time not working

### ISSUE THREAD

**Issue by a-nickol** [basecamp/local_time#148]
The feature for switching the time format from 12 am/p to 24h is not used for relative time.

**Comment by josefarias** [comment]
Hey @a-nickol, thanks for the PR. I'll check it out later. In the meantime, here's a way to achieve 24h formatting in relative time helpers: https://github.com/basecamp/local_time/issues/147#issuecomment-1777899892

**Comment by a-nickol** [comment]
I can polish the pr and add / correct tests and documentation, if it matches your expectations.

**Comment by a-nickol** [comment]
Maybe a rename of the keys would make it more clear, but would break when upgrading the library.

```
  formats: {
    12h: "%l:%M%P",
    24h: "%H:%M"
  }
```
