### ISSUE TITLE
Wrong timezone name used for daylight savings

### ISSUE THREAD

**Issue by hellcp** [basecamp/local_time#158]
I noticed when working with the library that the timezone displayed by JS when using `%Z` format string is `CEST` (Central European Summer Time) despite the fact that my current timezone is `CET` (Central European Time), and it's not currently summer, at least not in Europe. Those two timezones are seasonally different and off by one hour, which makes this confusing to users

**Comment by josefarias** [comment]
This should be fixed on the latest version, which was just released. Please let me know if not and I'll reopen. Thanks!

**Comment by hellcp** [comment]
Yup, that's much better, thanks!

**Comment by crespire** [comment]
Sorry to piggy back on a closed issue, but I am seeing this behaviour currently:

<img width="330" alt="image" src="https://github.com/basecamp/local_time/assets/36272822/1d7943d4-1ba4-48bc-a944-b69e88328174">

Any ideas as to what could be happening? The underlying data looks okay:
Anomalous EST value:
```html
<time datetime="2023-12-14T02:02:42Z" data-local="time" data-format="%b %-d, %Y %H:%M %Z" title="December 13, 2023 at 9:02pm EST" data-processed-at="2024-04-18T14:09:10.946Z" data-localized="">Dec 13, 2023 21:02 EST</time> (4 months ago)

```

Compared with a correct EDT value:
```html
<time datetime="2024-04-04T19:42:17Z" data-local="time" data-format="%b %-d, %Y %H:%M %Z" title="April 4, 2024 at 3:42pm EDT" data-processed-at="2024-04-18T14:09:10.945Z" data-localized="">Apr 4, 2024 15:42 EDT</time> (14 days ago)
```
