### ISSUE TITLE
3.0 changelog

### ISSUE THREAD

**Issue by taylorthurlow** [basecamp/local_time#160]
Can the changelog be updated to reflect the 2.x to 3.x breaking changes? It's not really clear at first glance what the breaking changes are, and I have a lot of projects with this dependency to update.

**Comment by josefarias** [comment]
@taylorthurlow if you can install the library, then you should be good to go.

**Comment by josefarias** [comment]
Gonna keep this open while I write up the full changelog

**Comment by josefarias** [comment]
Done in https://github.com/basecamp/local_time/commit/c207c7cc11d0b5b6fedc32e65f729ac8a8849e30. Thanks for the call out!

Special mention to @alesolano, @a-nickol
