### ISSUE TITLE
Sprockets installation instructions for v3

### ISSUE THREAD

**Issue by arinchoi03** [basecamp/local_time#161]
I am having trouble bumping our version from 2.1.0 to 3.0.2. We do not use importmaps or yarn, so both installation instructions do not seem to serve our purposes, unless we are meant to add importmaps / yarn to our bundle purely for the sake of installing this gem. 

Is there a way to preserve using the using the assets pipeline?

Currently we have in our `app/assets/javascripts/admin.js`:
```
//= require local-time
```

I did look through the related PRs that implemented this change, but wasn't able to figure it out - thank you in advance!

**Comment by josefarias** [comment]
Hey! If you have the `local_time` gem in your `Gemfile`, then you might be able to do this:

```js
//= require local-time.es2017-umd.js
LocalTime.start()
```

If you're not using the gem, or if you want to keep using `//=require local-time`, then I'd suggest downloading the UMD build found in https://github.com/basecamp/local_time/tree/main/app/assets/javascripts (look for the file with the `-umd.js` suffix) and putting it in `<app_root>/vendor/javascript/local-time.js`. Then your existing code should work fine.

Seems like you're still using Sprockets for your JS processing. That's okay! I'd suggest you consider migrating to use `importmap-rails` if time allows. It's the new default for handling JS in the asset-pipeline. Sprockets is still the default for css, though.

**Comment by arinchoi03** [comment]
Thank you! This worked for us. We will have updating to `importmap-rails` on our nice-to-have list of chores, since our app is sunsetting soon, but glad to have this fix in the meantime! :)
