### ISSUE TITLE
Browser error "The requested module 'local-time' does not provide an export named 'default'" 

### ISSUE THREAD

**Issue by epugh** [basecamp/local_time#162]
I'm updating local_time for my opensource project Quepid, and this is the first time enabling importmaps.   I am attempting to run sprockets and importmaps next to each other, so for importmaps I have a `application2.js` file.   

In chrome I get this error in the console:

```
Uncaught SyntaxError: The requested module 'local-time' does not provide an export named 'default' (at application2-63b9b5e9196a96eb0dc8c6ea2d0ffeb417e0e2e284501f0943faa6765ce1c6ad.js:4:8)
```

While in Firefox I get:

```
Uncaught SyntaxError: ambiguous indirect export: default
```

Both refer to this line in my `application2.js` file:

```
import LocalTime from "local-time"
```

Looking at the rendered HTML it seems to make sense:
![image](https://github.com/basecamp/local_time/assets/22395/3e8d7540-74cb-4b71-88d9-8e508a68a91d)

The PR that demonstrates my changes is https://github.com/o19s/quepid/pull/939

Would love any advice!

**Comment by epugh** [comment]
Some days it feels like when you open the issue, that's when you find the page that answers your problem.   There appears to be a bug, and I found some tips on #113 that worked.  Specifically, I changed my pin to `pin "local-time", to: "vendored-local-time.js"# @3.0.2` and renamed `vendor/javascript/local-time.js` to `vendor/javascript/vendored-local-time.js` and it all started working!

**Comment by josefarias** [comment]
@epugh I see in your PR you have multiple configurations that seem to be conflicting with each other.

The latest version of your PR has you linking the library in both your sprockets manifest and in importmaps.rb. In sprockets, you're linking the UMD build, while in importmaps you're linking the vendored version, which is the ESM build. These are not meant to work together, you should pick one instead.

Further, in the image you shared, you're linking to the UMD version from your importmap. I'd assume that's from a previous version of the PR.

The problem in https://github.com/basecamp/local_time/issues/113 should not be present anymore. We use the standard configuration in HEY, in production. And the fix in https://github.com/basecamp/local_time/issues/113 seems to have worked for other reporters. I think this points to a misconfiguration in your app.

You should be able to just have this in your importmap:

```rb
pin "local-time" # @3.0.2
```

Plus the vendored ESM build in `./vendor/javascript/local-time.js`. That should be enough as long as you're not also importing the library some other way.

Closing for now but let me know if you find a way to reproduce in a more minimal setup that doesn't potentially conflict with loading the library. I'll gladly take another look.

Note that you can also choose to use sprockets without importmaps following these instructions: https://github.com/basecamp/local_time/issues/161
