### ISSUE TITLE
UTC times seem to stay in UTC time

### ISSUE THREAD

**Issue by sheffler** [basecamp/local_time#35]
In my application, no user time zone is set.  All times are in UTC.

record.created_at renders as
   "2015-01-08 18:25:41 UTC"

and when used with <%= local_time(record.created_at) %>

it renders as
<time data-format="%B %e, %Y %l:%M%P" data-local="time" datetime="2015-01-08T18:09:28Z">January  8, 2015  6:09pm</time>

which ultimately displays as "6:009PM" even though it is "10:09AM" where I am (PST)

It seems the time is just staying in UTC.

I had hoped that UTC would display in the zone of the browser automatically.  Perhaps that is a configuration option.

**Comment by javan** [comment]
It is supposed to work as you hoped and display the browser's local time. Can you inspect the `<time>` element in the web inspector and paste it here? It should have a `datetime` attribute in UTC and its innerHTML should be localized.

**Comment by sheffler** [comment]
Here is a copy from the inspector
<time data-format="%B %e, %Y %l:%M%P" data-local="time" datetime="2015-01-08T21:04:48Z">January  8, 2015  9:04pm</time>
thx -T

**Comment by javan** [comment]
Can you paste the element's complete HTML please? It should look something like: 

```html
<time data-format="%l:%M%P" data-local="time" datetime="2014-12-19T17:16:27Z" title="December 19, 2014 at 12:16pm EST" data-localized="true">12:16pm</time>
```

A screenshot from the inspector would work too.

**Comment by sheffler** [comment]
Ack!  It needs to be markdown-escaped here!  Here goes.

```html
<time data-format="%B %e, %Y %l:%M%P" data-local="time" datetime="2015-01-08T21:04:48Z">January  8, 2015  9:04pm</time>
```

**Comment by javan** [comment]
It appears that the LocalTime JavaScript hasn't run, which explains why you're seeing an unconverted time. If it had run, the elemnt would have a `data-localized="true"` attribute.

Did you follow all of the [install instructions](https://github.com/basecamp/local_time#installation)? In a browser console, can you access `window.LocalTime`?

**Comment by sheffler** [comment]
That was it - and you have verified that I cannot follow instructions.  I added the gem and did the 'bundle install', but I forgot to add '//= require local_time' to application.js.

Thanks for the diagnosis - appreciated.

**Comment by javan** [comment]
:beers:

**Comment by whatasunnyday** [comment]
I ran into this as well. I'm not sure what you think of this, would you consider moving the installation instructions further up in the README? I know it's for dummies like me but when I saw the example, I didn't even think to scroll down.
