### ISSUE TITLE
undefined method `local_time' error

### ISSUE THREAD

**Issue by aman199002** [basecamp/local_time#4]
I have installed gem 'local_time' in my application and require 'local_time' in application.js properly.
But, when i try to use local_time helper. Its showing error that local_time is not defined.

```
= local_time(User.first.created_at)
=>
undefined method `local_time' for #<#<Class:......>
```

**Comment by ultramaroon** [comment]
I had this issue, but it was all my fault and it was because I had installed the gem 'localtime' and not 'local_time'.. Just putting this here in case someone is as dumb as me and comes upon this thread.

**Comment by vibhor86** [comment]
It took me a while to realise that I was running the dev app server using Pow and required to restart it

**Comment by pfeifferj** [comment]
I still have the NameError after correct installation and multiple puma restarts. Using Rails 5.0.2 and ruby 2.4.0 on a ubuntu VM.
