### ISSUE TITLE
Safari complains about selector

### ISSUE THREAD

**Issue by hakunin** [basecamp/local_time#42]
Hi I get this in my JS error logs:

An invalid or illegal selector was specified (selector: 'time[data-local]:not([data-localized])' error: Invalid selectors: time[data-local]:not([data-localized]))

https://github.com/basecamp/local_time/blob/master/app/assets/javascripts/local_time.js.coffee#L196

The browser is `mobile safari 5.0.2`.

**Comment by josefarias** [comment]
This shouldn't be happening anymore on modern safari. Please comment if it is. Thanks!
