### ISSUE TITLE
'%-d' not supported

### ISSUE THREAD

**Issue by colbywhite** [basecamp/local_time#45]
This is more of a feature request than a bug, but `%-d` isn't supported, while `%d` is. 

Recreate with the following: 
```javascript
LocalTime.strftime(new Date, '%a %b %d %l:%M %p %Z')
LocalTime.strftime(new Date, '%a %b %-d %l:%M %p %Z')
```

Output:
```
"Tue Sep 01 12:38 PM CDT"
"Tue Sep %-d 12:38 PM CDT"
```

Expected Output
```
"Tue Sep 01 12:38 PM CDT"
"Tue Sep 1 12:38 PM CDT"
```

From the ruby [DateTime](http://docs.ruby-lang.org/en/2.2.0/DateTime.html#method-i-strftime) doc:
```
    %d - Day of the month, zero-padded (01..31)
            %-d  no-padded (1..31)
```

If I can find where this is happening when I'm free, I'll take a stab at it myself.

**Comment by javan** [comment]
The `-` modifier isn't universal across all strftime implementations, but I'd consider a PR to add support for it. In the meantime, you can use `%e`:

```js
LocalTime.strftime(new Date, "%d")
=> "01"

LocalTime.strftime(new Date, "%e")
=> "1"
```
