### ISSUE TITLE
No support for prefixing with minus to eliminate leading zeros

### ISSUE THREAD

**Issue by rscherf** [basecamp/local_time#47]
Using the `-` format for newer versions of `strftime` doesn't output correctly. Since there is a dependency on the system's `strftime` version, it seems like it could support both (and just always fall back to `%m` and `%d`. Obviously using `%e` instead of `%-d` is an option for day, but there isn't a great alternative for month.

Consider this example:
```ruby
"Ends #{ local_time(auction.ends_at, '%m/%d at %l:%M%P %Z') }".html_safe
```

yields the correct date:
```
Ends 09/24 at 2:13pm CDT
```

Meanwhile, 
```ruby
"Ends #{ local_time(auction.ends_at, '%-m/%-d at %l:%M%P %Z') }".html_safe
```

yields this incorrectly:
```
Ends %-m/%-d at 2:13pm CDT
```

which should yield:
```
Ends 9/24 at 2:13pm CDT
```

**Comment by javan** [comment]
As noted in the end of [this section](https://github.com/basecamp/local_time#time-and-date-helpers) in the README, the JavaScript `strftime` implementation isn't fully compatible with Ruby's. I'd be happy to review a pull request that brings it up to speed.
