### ISSUE TITLE
local_time does not display proper time when put inside bootstrap's tooltip

### ISSUE THREAD

**Issue by wakarana1** [basecamp/local_time#51]
I'm having a problem displaying the correct time when I put local_time inside of Bootstrap's tooltip. Formatting works, but the time remains `UTC` time instead of `PDT` time.

```
<% @product.users.each do |user| %>
  <% if user.active %>
    <img src="<%= user.image %>" class="user-image" data-toggle="tooltip" data-placement="bottom" data-html="true" title='Last Logged in: <br> <%= local_time(user.updated_at) %>' />
    <% end %>
 <% end %>
```

Would display
```
Last Logged In:
December 18, 2015 3:53am
```
instead of
```
Last Logged In:
December 18, 2015 7:53pm
```
So it does format the date, it just doesn't change the date to my local time zone like I wanted it to.

**Comment by javan** [comment]
The `local_time` helper renders a `<time>` tag so it's not suitable for using inside a `title` attribute (or any attribute).
