### ISSUE TITLE
confusion between Arabia Standard Time (UTC+3) and Atlantic Standard Time (UTC-4)

### ISSUE THREAD

**Issue by tansaku** [basecamp/local_time#59]
Is it possible that the local_time gem may confuse some timezones - for example Arabia Standard Time (UTC+3) and Atlantic Standard Time (UTC-4) are both abbreviated to AST.

See https://github.com/AgileVentures/WebsiteOne/issues/1097 for more details.

Any idea if there is a quick fix for this sort of thing?

**Comment by javan** [comment]
LocalTime uses the abbreviations provided by the browser and those are the standard abbreviations. Nothing it can do to help, sorry!

<img width="283" alt="screen shot 2016-06-14 at 12 34 31 am" src="https://cloud.githubusercontent.com/assets/5355/16023990/7bcc7c3a-318d-11e6-963b-ec914dd273ff.png">

<img width="603" alt="screen shot 2016-06-13 at 5 35 13 pm" src="https://cloud.githubusercontent.com/assets/5355/16023996/820195ae-318d-11e6-8c0c-ba7c0acdf439.png">
http://www.timeanddate.com/time/zones/

**Comment by tansaku** [comment]
thanks @javan :-)
