### ISSUE TITLE
The gem is slow in converting

### ISSUE THREAD

**Issue by akashaggarwal7** [basecamp/local_time#63]
Sometimes the gem takes maybe more than a minute to convert the text using the `local_time_ago` helper. Anyone aware about this and/or knows a solution? I'm also using turbolinks, if that can be an issue.

**Comment by javan** [comment]
Try the 2.0 branch: https://github.com/basecamp/local_time/pull/55

**Comment by akashaggarwal7** [comment]
It's true the problem occurs when I click a link in the app.  Switched to `:ref => '9fae425'`, still the same.

**Comment by jasonivers** [comment]
I'm experiencing slow down, as well, though I'm just using local_time, not local_time_ago.  The exact behavior I'm seeing might be helpful in figuring it out:

The affected timestamp is in a chat interface.  When the interface loads, all of the times are NOT local.  If I wait long enough, they will eventually be localized.  If I send a _new_ message, however, which gets loaded via websockets and AJAX, it _immediately_ updates all of the existing timestamps, the new one shows up off, then after a minute or so, updates.

It seems like the delay, then, is something to do with loading or with waiting before executing.

**Comment by michaelklem** [comment]
After updating to the 2.0 branch, we have had no issues. Thanks!
