### ISSUE TITLE
JS support for non-padded values (%-d)

### ISSUE THREAD

**Issue by stevenspiel** [basecamp/local_time#65]
If I have a DateTime object (`datetime = DateTime.parse('5/8/10 8:53')`), and `strftime` it with non-padded indicators (like `%-e` and `%-I`), in ruby-land, it all renders correctly

```rb
Time.now.utc.strftime('%b %-e, %Y %-l:%M %p') # => "Aug 5, 2010 8:53 AM"
```

and it works great with `local_time`

```rb
local_time(Time.now.utc, Time.now.utc) 
#=> <time datetime=\"2010-08-05T08:53:00+00:00\" data-local=\"time\" data-format=\"%b %-e, %Y %-l:%M %p\">Aug 5, 2010 8:53 AM</time>
```

But the javascript seems to lack compatibility

```html
<time datetime="2010-8-5T08:53:00Z" data-local="time" data-format="%b %-e, %Y %-l:%M %p" title="August 8, 2010 at 8:53am EST" data-localized="true">Aug %-e, 2010 %-l:53 AM</time>
```

It ultimately renders `Aug %-e, 2010 %-l:53 AM`, which is not expected.

**Comment by ted-hanson** [comment]
don't know if you care, but I have a fork with this feature for the options that need it (I think)

**Comment by ted-hanson** [comment]
https://github.com/ted-hanson/local_time you can take a look it's a small commit
