### ISSUE TITLE
Some kind of cache

### ISSUE THREAD

**Issue by inShu** [basecamp/local_time#66]
Hi,
I'm using local time like this:
`<td><%= local_time(node.last_seen) %></td>`
And when I'm opening the page I see non-converted time:
`<time datetime="2017-03-30T17:36:39Z" data-local="time" data-format="%B %e, %Y %l:%M%P">March 30, 2017  5:36pm</time>`
After I'm pressing F5 to refresh the page:
`<time datetime="2017-03-30T17:36:39Z" data-local="time" data-format="%B %e, %Y %l:%M%P" title="March 30, 2017 at 8:36pm RST" data-localized="true">March 30, 2017 8:36pm</time>`

So, it's smells like some kind of caching. Maybe I'm cooking gem in wrong way?

Thank you.

**Comment by Wherefour** [comment]
+1 for this, I'm noticing the same thing. I found a closed thread with a similar situation and they described putting this in application.js as a workaround. I'm not sure why it's not firing on the first page load, though:
```

document.addEventListener("turbolinks:load", function() {

  LocalTime.run();

});
```

**Comment by inShu** [comment]
Looks like a kludge which pressing F5 for users.

Thank you.

Could you please give me a link to issue?

**Comment by Wherefour** [comment]
https://github.com/basecamp/local_time/issues/41

If you figure out a better way than this, let me know? Agreed that this feels like a kludge.

**Comment by PeterWooster** [comment]
I've noticed that recently, sometime after Rails 5, this fails when the link comes from TurboLinks.

When I first load the page, or if it's loaded from a link outside the app, or after a refresh the time is correct and the link looks like:

`<time datetime="2017-04-14T15:58:36Z" data-local="time" data-format="%B %e, %Y %l:%M%P" title="April 14, 2017 at 11:58am EDT" data-localized="true">April 14, 2017 11:58am</time>
`
However if I navigate using an internal link I see:

`<time datetime="2017-04-14T16:00:19Z" data-local="time" data-format="%B %e, %Y %l:%M%P">April 14, 2017  4:00pm</time>
`
Disabling TurboLinks fixes the problem.

**Comment by PeterWooster** [comment]
Calling  ` LocalTime.run();` on turbolink:load as suggested by @Wherefour fixed this for me.  I was already installing datepicker on that event:
```
$(document).on("turbolinks:load", function() {
    LocalTime.run();
    
	$('.datetime').datetimepicker({  ...
```
