### ISSUE TITLE
Changing actual time

### ISSUE THREAD

**Issue by jasonivers** [basecamp/local_time#68]
This is my code:
`<%= local_time(conversation.updated_at, '%l:%m %p') %>`

This produces:
`<time datetime="2017-05-22T23:00:35Z" data-local="time" data-format="%l:%m %p" title="May 22, 2017 at 4:00pm PDT" data-localized="true">4:05 PM</time>`

Why does it say "4:05" in the actual text that displays, in spite of the fact that both the time stamp and even the title both clearly end in ":00"?

This is bizarre, and I haven't the foggiest idea where to even look... it's doing this with many different times, too (:24, :23, :39, etc.).  It's not the javascript doing it... when I look at what comes back from my server, the "HTML time" ends in :05, as well:
`<time datetime="2017-05-22T23:00:35Z" data-local="time" data-format="%l:%m %p">11:05 PM</time>`

Anyone have any help for me?

**Comment by javan** [comment]
```
%m - Month of the year, zero-padded
%M - Minute of the hour (00..59)
```

:)

**Comment by jasonivers** [comment]
Thank you... spent way too much time on that yesterday, amidst way too many other things.  Never even thought of that.
