### ISSUE TITLE
ActionView::Template::Error (couldn't find file 'local_time' with type 'application/javascript')

### ISSUE THREAD

**Issue by Hamada92** [basecamp/local_time#74]
Hey guys, thanks for the great gem.

I just upgraded to Rails 5.0.3 and local_time 2.0 and I get this error: 

```
ActionView::Template::Error (couldn't find file 'local_time' with type 'application/javascript'
Checked in these paths:
....
....
  /Users/Ahmad/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/local_time-2.0.0/app/assets/javascripts
```

It seems to have installed the gem but can't find it. Reverting back to 1.0.3 the error goes away. 

Thanks

**Comment by javan** [comment]
> Renamed `local_time.js` to `local-time.js`

https://github.com/basecamp/local_time#version-history

✌️
