### ISSUE TITLE
handle nil 

### ISSUE THREAD

**Issue by jstewsy** [basecamp/local_time#80]
If a time passed to `local_time_ago` happens to be `nil`, it will throw an error:

```
undefined method `to_time' for nil:NilClass
```

would it be possible to have `local_time_ago` handle this gracefully by returning `nil` or `''`?

**Comment by javan** [comment]
Probably best to handle that in your own application if you're expecting an optional value:
```erb
<%= local_time_ago(time) unless time.blank? %>
```
Otherwise we'd be silently covering up what might truly be an underlying error state.

**Comment by jstewsy** [comment]
yup, good call. thank you!

**Comment by januszm** [comment]
Honestly, it's a helper, not a model, and I would expect it to help write less code. Opinions are divided here, but imo this helper should silently ignore `nil`. Otherwise, you may have to do a lot of workaround in larger applications.
