### ISSUE TITLE
time zone is incorrect when loading but changes sometime later

### ISSUE THREAD

**Issue by birthdaycorp** [basecamp/local_time#85]
The time in my app is incorrect when reloading the page, but changes to the correct time at some point later (usually within a split second, but sometimes it takes a few). I've followed everything in the docs to the tee, and I have `LocalTime.run();` in my Action Cable function as suggested in [this answer](https://github.com/basecamp/local_time/issues/41#issuecomment-232523455). 

How can I make this work so that the seams are not showing?

**Comment by javan** [comment]
What version of Local Time are you using? [As of 2.0.0](https://github.com/basecamp/local_time/blob/master/CHANGELOG.md), `<time>` elements should be detected and converted automatically (and nearly instantaneously) without the need to call `LocalTime.run()`.

**Comment by birthdaycorp** [comment]
That was it! The default gem at rubygems.org was at 1.0. Updated that and it fixed everything. Thank you!
