### ISSUE TITLE
How to localize on server side?

### ISSUE THREAD

**Issue by mabras** [basecamp/local_time#87]
I have a non-english Rails app which use `local_time` gem:
```ruby
<%= local_time_ago(obj.created_at) %>
```
I am trying to localize it. On the client side, everything is working just fine. The text shows in my custom language. But on the first load of the page I get the english text (I guess this is the server side text?). How to set the locale of `local_time` gem on server side? I have already set `config.i18n.default_locale`

**Comment by mjansing** [comment]
I solved this by bypassing local_time_ago helper method and using time_tag with data attributes:

```
<%= time_tag(created_at, 'data-local': 'time-ago')  %>
```

**Comment by josefarias** [comment]
It sounds like maybe the locale is being set after the initial rendering of the page. If you're using Turbo, then subsequent navigations would have the correct locale applied before rendering and, thus, display the expected language.

I'd need more information to say for certain. Specifically, how/when/where the locale is being applied and any details about how your stack might be handling native browser navigation (using Turbo, for example).

Please let me know if this is still happening on `main`. Closing for now.
