### ISSUE TITLE
how to use local_time_ago in js file and in controllers?

### ISSUE THREAD

**Issue by RohitVenturit** [basecamp/local_time#88]
my requirement of adding this from js , so how to use local_time_ago in js file and in controllers?

**Comment by barrywoolgar** [comment]
It is not clear what you need help with. Could you provide some more details?

**Comment by josefarias** [comment]
If you mean Rails controllers, you should really be calling the `#local_time_ago` helper from the view instead.
Calling from within JS is technically possible but not what the library is built for, so I'd advise against it.

Ultimately, the `#local_time_ago` helper renders a `<time>` element. You'd usually want that directly in your HTML templates.
