### ISSUE TITLE
Timezone abbreviations not always correct.

### ISSUE THREAD

**Issue by randyL78** [basecamp/local_time#94]
When using `%Z` format specifier, some abbreviations are not the same as in abbreviation tables such as: https://www.timeanddate.com/time/zones/.

For instance, Alaska Daylight Time should be abbreviated as `AKDT` and instead is showing as `ADT` which is Atlantic Daylight time.

Gem version used: 2.0.1

Steps to reproduce:
1. Include `<%= local_time(Time.now, format: "%I:%M %p %Z") %>` in a test view.
2. Force a geolocation using the browser's dev tools. Use Location name: Anchorage, Lat: 61.2181, Long: -149.9003, Timezone ID: America/Anchorage (In Chrome this is done by opening Dev tools and selecting (settings)>>more tools >> sensors, and then click on `add location`)

**Comment by kwhandy** [comment]
@randyL78 Any updates for this issue?

**Comment by josefarias** [comment]
Thanks for reporting this. It should be addressed on main now per https://github.com/basecamp/local_time/pull/142

We hope to get the fix released soon.
